### ISSUE TITLE
Doesn't work on L5.1

### ISSUE THREAD

**Issue by digixweb** [dwightwatson/rememberable#10]
Using for instance:

$users = User::where("id", ">", "1")->remember(10)->take(5)->get();

Gives the expected result (no errors). But reloading the page, I see that mysql simply fires the 5 queries again and again....

**Comment by dwightwatson** [comment]
Could you please confirm which version of Laravel and rememberable that you are using (specific versions)?

**Comment by dwightwatson** [comment]
Also, can you confirm that your cache driver is not set to `array`?

**Comment by digixweb** [comment]
Laravel 5.1.20 (LTS)
CACHE_DRIVER=file

**Comment by digixweb** [comment]
According to your installation info, this has been added to my composer:
"watson/rememberable": "^1.0"

**Comment by dwightwatson** [comment]
You'll need to check your `composer.lock` file to see what version of `watson/rememberable` is installed. Laravel `5.1.20` introduced a compatibility issue with version `1.0.0`, so `1.0.1`  was released. Please run a Composer update to ensure you're running the latest version of the package with the compatibility fix and let me know how you go.

**Comment by digixweb** [comment]
Actually 1.0.1 was already installed. Composer.lock:
            "name": "watson/rememberable",
            "version": "1.0.1",

**Comment by dwightwatson** [comment]
I haven't been able to replicate this at all, I've also got this update working in multiple production environments.

Are you able to provide more code, or even a sample project, that exhibits this issue so I can try and work out what is going wrong?

**Comment by digixweb** [comment]
I will try to create a sample project for this later this week.

The particular model has certain relationships attached to it. Could this be a problem?
Btw, is this also supposed to work witht paginate() queries?

**Comment by dwightwatson** [comment]
It should work with paginate queries, though it might not cache the total count - I haven't tested that.

As far as relationships go, they would need to be cached too.

```
$users = User::where("id", ">", "1")
    ->with(['posts' => function ($q) { $q->remember(10); }])
    ->remember(10)
    ->take(5)
    ->get();
```

**Comment by digixweb** [comment]
Adding the code for relationships seems to fix the issue. Thanks.

**Comment by dwightwatson** [comment]
No worries, glad that cleared it up.

**Comment by rusmanarief** [comment]
@digixweb what do you mean by adding the code to the relationship? do you mean to add the remember() to the hasMany('posts') ? or to add use Rememberable in Post Eloquent Model?

**Comment by dwightwatson** [comment]
See my code example above, where I added `remember()` to the query inside of the `with()` method.

**Comment by rusmanarief** [comment]
ok thanks @dwightwatson

**Comment by dcshoes23** [comment]
@dwightwatson You should put [this](https://github.com/dwightwatson/rememberable/issues/10#issuecomment-149886651) in your readme file, I ran into this issue and had to go digging to find this.

**Comment by dwightwatson** [comment]
Will do, thanks!
