### ISSUE TITLE
Remove generated cache by rememberable

### ISSUE THREAD

**Issue by digixweb** [dwightwatson/rememberable#11]
Sometimes I want to force a refresh of the cache that has been set by rememberable. Something like: Cache::forget('key'); However I don't know the key and if this way is possible at all?

**Comment by dwightwatson** [comment]
I think there are two approaches here. First is to use a custom cache key and forget the item that way.

```
User::latest()->remember(60, 'users.latest')->get();

Cache::forget('users.latest');
```

The second is to get the default cache key from the query and then forget it that way.

```
$cacheKey = User::latest()->getCacheKey();

Cache::forget($cacheKey);
```

Hope this helps!

**Comment by digixweb** [comment]
Resetting the cache works this way. However..setting a custom cache key returns an empty cache.

**Comment by digixweb** [comment]
Is this something you intend to fix? Great extension for Laravel but I need this working with a custom key. Thanks in advance!

**Comment by dwightwatson** [comment]
Sorry, didn't see the last message. I'm not sure I understand this part: `setting a custom cache key returns an empty cache`.

Do you mean if you set a custom cache key, like in my first example, the cache isn't actually persisting and hitting the database on every request? Or could you perhaps clarify the problem in another issue?

Would like to take a look at this and sort it out if possible, also happy to accept a PR that resolves the issue.

**Comment by digixweb** [comment]
It is not hitting the database on every request, but it just returns an empty value when retrieving it for the second, third, etc. times. In case I put Cache::forget('users.latest'); directly after setting the cache, it keeps hitting the database (as expected).

**Comment by dwightwatson** [comment]
I can't replicate this at all.

```
$users = \App\User::latest()->take(5)->remember(5, 'users.latest')->get();

dump(DB::getQueryLog());
```

The first request makes one database query and following requests do not.

```
Cache::forget('users.latest');

$users = \App\User::latest()->take(5)->remember(5, 'users.latest')->get();

dump(DB::getQueryLog());
```

The query is performed on every request.

Can you try performing a complete flush of your cache, or try a different cache driver and see if the results change?

**Comment by digixweb** [comment]
This issue seems to occur only with paginate();
So for instance:
$users = \App\User::latest()->remember(5, 'users.latest')->paginate(10);

**Comment by dwightwatson** [comment]
Again, I am still totally unable to replicate this on a fresh install of Laravel. Both the `COUNT` and `SELECT` queries with pagination are being cached on my end. I suspect this issue will be something to do with your app's configuration.

If you're able to show a complete demonstration of this in a fresh install of Laravel please create a new issue as it is actually a different issue to this one and I'll take a look at it.

**Comment by digixweb** [comment]
I used both Memcached and file driver. I also flushed the cache folder. I can see that a cache file is written. However It is empty. Very strange.

1448366994a:1:{i:0;O:8:"stdClass":1:{s:9:"aggregate";i:312;}}

I will try to see if I can replicate this on a fresh install.

**Comment by agoalofalife** [comment]
Hi guys! @digixweb @dwightwatson
Maybe anyone will need in answer
ok, then get cachpPrefix, need get `Watson\Rememberable\Query\Bulder` from your request

Example, if just call method how this:

```
$cacheKey = User::latest()->getCacheKey();

Cache::forget($cacheKey);
```
You got `Base` Builder from Laravel, but us need `Watson\Rememberable\Query\Bulder` 
well like so

```
$cacheKey = User::latest()->getQuery()->getCacheKey();

Cache::forget($cacheKey);
```
This will is working!
