### ISSUE TITLE
Question: Query Builder?

### ISSUE THREAD

**Issue by snipiba** [dwightwatson/rememberable#15]
Is any way to get it on query builder not only as db Eloquent?
when i try it on 
`
DB::table('table')->join('table','t1.field','=','t2.field')->where('t1.field',$var)->remember('1440')->get();
`

i got an error with Builder.php

**Comment by dwightwatson** [comment]
From memory I tried to find a good way to do this for the initial release, but I couldn't do it in a nice way. At this stage it's Eloquent only, I'm afraid. Happy to accept a PR that solves it nicely.
