### ISSUE TITLE
Please answer these questions..

### ISSUE THREAD

**Issue by deep88** [dwightwatson/rememberable#16]
Do this package caches the eloquent queries with paging efficiently..

Do this package clears cache on model update..

is there a way to cache all database queries..

is there a way to implement tag to caching queries..

pls reply soon....Thank you..

**Comment by dwightwatson** [comment]
- Yes, this will cache paginated queries. However, I don't believe it will cache the additional count total query.
- No, this does not clear cache on model updates. It is caching raw SQL queries, it has no knowledge of the models/data itself.
- You could subclass this package's query builder and adjust it to cache all queries if you liked. I'd probably not go this way to be honest, as there are definitely times where you would want to ensure you're getting fresh data.
- You should be able to call the `cacheTags()` method on the query to provide cache tags in that manner (if your cache driver supports them).

Hope that answers your questions.

**Comment by dwightwatson** [comment]
Just following up on this, I believe the count query when getting paginated results is also cached too (after looking at the code a little more).
