### ISSUE TITLE
Compatibility with Laravel 5.2.3

### ISSUE THREAD

**Issue by ejeanneaubc** [dwightwatson/rememberable#19]
Hi !

I think the vendor isn't compatible with the last version of Laravel (at the moment 5.2.3).

Can you help please ?

Thank's a lot !

Have a nice day !

Emmanuel.

**Comment by dwightwatson** [comment]
The latest version of Laravel is `5.2.31`. Is this what you're using?

Could you please go into a little more detail about what isn't working?

**Comment by ejeanneaubc** [comment]
Hi !

I'm sorry, i think the problem is related with my memcached configuration because i see in the phpinfo "json support no" i think when i try to store a result query (object type) i've got an error. Why cache system don't force when put "serialize" and "unserialize" when get the result ?

**Comment by dwightwatson** [comment]
Not sure - I'd double-check you've updated to the latest version of Laravel (again, the latest version is _not_ `5.2.3`). Also, try a different cache driver (see if the issue persists with the file or database cache driver instead). Finally, you could try using a development environment like Laravel's Homestead which would have Memcache setup to work correctly.
