### ISSUE TITLE
For Laravel 5 eager loading remember is not working

### ISSUE THREAD

**Issue by prakash-malviya** [dwightwatson/rememberable#2]
I have below query which is not cache proper using remember, rest will work fine as expected.
$products = $category->products()->with("inventory","tierPrice","images","url","attrs","attrs.values","attrs.values.images","attrs.values.option","attrs.values.option.image")->active()->orderBy($sort_by, $sort_order)->remember(1440)->paginate($limit);

Any help or suggestion are appreciated !!!

Thanks...

**Comment by dwightwatson** [comment]
As I understand it this was how it operated in Laravel 4 - when you eager load only the initial query is cached and the queries for the related objects are performed every time. One of the goals for this project is actually to add the ability to cache the results of the related queries as well. I've been working on this slowly, I don't have an ETA as such but it is on the roadmap.

**Comment by wmather** [comment]
If you want to remember the eager loaded queries then you do this (at least in L4)

`->with(['relation' => function($q) { $q->remember(15); }])`

**Comment by prakash-malviya** [comment]
Thanks for your reply  !! I have implemented in L5 with PHP trait concept.

**Comment by scofield-ua** [comment]
@prakash-malviya can you please share your solution?
