### ISSUE TITLE
Laravel dependency

### ISSUE THREAD

**Issue by clemorphy** [dwightwatson/rememberable#23]
Hi!

Can rememberable be used without Laravel, only with Eloquent ? Or does it need Laravel ?

I plan to use Slim and Eloquent ( http://www.slimframework.com/docs/cookbook/database-eloquent.html ) but I am looking for a way to cache SQL queries.

**Comment by dwightwatson** [comment]
At the moment it's a little coupled to Laravel as it expects to use Laravel's `Cache` facade.

You could get around this if you're using Laravel's cache implementation too, or another implementation that is compatible with Laravel's cache contract. You could override the [`getCache()`](https://github.com/dwightwatson/rememberable/blob/master/src/Query/Builder.php#L133-L143) method on your base model and instead return your own implementation.

I hope this makes sense, and I'll close the issue for now, but let me know if you get it working - it's something we could add to the documentation to help people trying a similar setup.
