### ISSUE TITLE
Collisions with other trait methods

### ISSUE THREAD

**Issue by hatung** [dwightwatson/rememberable#24]
other Trait also use newBaseQueryBuilder function.
How can I deal with traits with methods of same name?

**Comment by dwightwatson** [comment]
Which trait?

PHP doesn't support multiple inheritance, so you're going to have to sort it out manually.

Override `newBaseQueryBuilder` in your own base model and then merge the logic from Rememberable and whatever other traits you want to use. It'll be up to you to maintain the compatibility between various traits.

Hope this helps!
