### ISSUE TITLE
all  method can not use 

### ISSUE THREAD

**Issue by michaelqxd** [dwightwatson/rememberable#31]
User::remember(10)->all()   failed

Call to undefined method App\Model\Rememberable\Query\Builder::all()

**Comment by dwightwatson** [comment]
Thanks for this, I'll be away from a computer for the next week but will be able to sort this out after then. 

For now, you can simply call get() instead of all(), you'll still get all the results. Hope this helps.

**Comment by dwightwatson** [comment]
After looking at this a little more I don't think we need to fix this. `all()` is only ever called directly on the model (i.e. `User::all()`). When performing any additional constraints you're always going to be using `get()` at the end of the chain so I think it's fine for that to continue here.

`User::remember(10)->get()`.
