### ISSUE TITLE
Way to disable caching (e.g. in dev environment)?

### ISSUE THREAD

**Issue by ghost** [dwightwatson/rememberable#32]
Just asking, is there a way to disable all caching from just one point?
Just came across a few issues that would've been solved had I remembered I was caching things.

**Comment by dwightwatson** [comment]
Two ways you might go about this;
1. Change the cache driver in development to `array` - this means whatever is cached will be cleared by the next request. It's important to note that this disables caching for your entire app, not just your database queries.
2. Use a environment/configuration variable to set how long to cache a query for. In production you could set this to however many minutes you want the item to be cached, and you could leave it as `NULL` in development (which I believe will mean no caching).

I hope this helps - let me know if there is anything else I can do to help.

**Comment by karmendra** [comment]
The issue with the 2nd method is we should restrict remembering same minutes in all my queries where I use it, or I need to have many env variables. I think a very optimum solution would be providing a env variable or, config file where we can enable/disable the remembering at once for every thing.

If it is acceptable for you I will work on it and submit a PR.

**Comment by dwightwatson** [comment]
But you could enable/disable remembering by changing the cache driver to array - what's the use-case where this isn't enough?

**Comment by karmendra** [comment]
Its not bad, Its just that its implicit. And to get to know about these 2 options that you mentioned above  in this issue, I had to search quite a bit before landing here.

May be you should consider putting it in documentation/readme.

**Comment by dwightwatson** [comment]
I don't think I'm a fan of making the query cache distinct from the app cache - it's the same thing under the hood and I think it becomes an unnecessary complication. 

Open to any PRs that want to highlight that in the docs.
