### ISSUE TITLE
Cannot redeclare class App\Model 

### ISSUE THREAD

**Issue by kristoff2016** [dwightwatson/rememberable#33]
I tried used this packages in localhost it is working as normal but when I move to my production it has the problem like above. any suggestion code how to use in model without any issue ? thank you

**Comment by dwightwatson** [comment]
Hard to tell without you supplying any code. Sounds like you have multiple definitions of `App\Model` in your codebase. Look through the code and make sure you only have one `App\Model`, and it should be in your `app/` directory.
