### ISSUE TITLE
Feature Request: Auto Purge Option

### ISSUE THREAD

**Issue by sarfraznawaz2005** [dwightwatson/rememberable#37]
This package would be great if there is an auto-purge option which flushes entire cache of a model if any record is updated, deleted or added?

Thanks

**Comment by dwightwatson** [comment]
Thanks, as discussed earlier (see #34 and earlier referenced issues) this is out of the scope of this project.

However, @ameliaikeda is working on a fork of this project (see [ameliaikeda/rememberable](https://github.com/ameliaikeda/rememberable)) which adds support for automatic flushing and a whole heap of other cool stuff, which would be worth checking out.
