### ISSUE TITLE
Support for Laravel Scout

### ISSUE THREAD

**Issue by Kovah** [dwightwatson/rememberable#38]
First of all thank you for this awesome package.

I implemented a search functionality into my app with Laravl Scout and the TNTSearch driver. Unfortunately I was not able to make it work due to the fact that Rememberable does not support the search method provided by Laravel Scout.
I get the following error while trying to search a specific item:

    Call to undefined method Watson\Rememberable\Query\Builder::search()

Is it possible to implement this into the pakage? Or is there a way to do this on my own?

Thanks fo the help. :)

**Comment by Kovah** [comment]
Whoops, my fault. Wrong query order.

For everyone who gets the same error: put your `where()` statements **after** the `search()` method like this:

    User::search('tommy')->where('group', 2)->get();

**Comment by dwightwatson** [comment]
Thanks for posting the answer too - good to know. Haven't actually got around to using Laravel Scout with this yet so should come in handy.
