### ISSUE TITLE
Usage with DB facade without models

### ISSUE THREAD

**Issue by rogervila** [dwightwatson/rememberable#42]
Hello,

I'm querying some data via `DB` facade, like this:

`\DB::connection('customconnection')->select('SELECT * FROM mytable')`

Is it possible to use the plugin here? How can I add the `Rememberable ` trait?

Thank you!

**Comment by dwightwatson** [comment]
Hey, unfortunately in it's current iteration this library only works with Eloquent models. From memory I looked into making it work with the DB facade but couldn't get it work the way I wanted. Happy consider any PRs that can introduce the functionality in a clean way.

I'd recommend just using the Cache facade, you'd need to check the docs but I think it's something like this...

```php
Cache::remember('foo.bar', 60, function () {
    DB::select('SELECT foo FROM bar');
});
```
