### ISSUE TITLE
Refresh the cache

### ISSUE THREAD

**Issue by Bolandish** [dwightwatson/rememberable#43]
Hi! 

I've got a large system running rememberable-plugin and it works really well.

Would it be possible to make a refresh-command which updates the result in the caching by the cachingtag?
It could be nice!

**Comment by dwightwatson** [comment]
Hey, thanks for the kind words.

I think this is better suited to writing a command specific to your app - it's going to depend on which models you have that use `rememberable` and which ones have a model cache key set. Could get complicated quickly.
