### ISSUE TITLE
How do I extends User model in Laravel 5.4?

### ISSUE THREAD

**Issue by hakimihamdan88** [dwightwatson/rememberable#44]
use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

**Comment by dwightwatson** [comment]
I'll work just the same. Import the class and then use it in the model as the documentation indicates. Let me know if you run into any trouble.

**Comment by hakimihamdan88** [comment]
@dwightwatson this code seems not working

class User extends Models
{

**Comment by dwightwatson** [comment]
```
class User extends Authenticatable
{
    use Rememberable, Notifiable;
```

**Comment by hakimihamdan88** [comment]
@dwightwatson oh, no need to extends Model?
so I need to repeat use Watson\Rememberable\Rememberable; on every model?

**Comment by dwightwatson** [comment]
Authenticatable extends from Model, for memory, so it will still work. You'll need to add `Rememberable` to any model you want to call `remember()` on.
