### ISSUE TITLE
morphTo caching is not working.

### ISSUE THREAD

**Issue by jhemmmm** [dwightwatson/rememberable#48]
Just like the title say. When I tried to ->remember(10). The caching is working.

**Comment by dwightwatson** [comment]
Not very clear on what's happening here. You say it's not working, then it is?

Going to need some sample code if you want help with this one.

**Comment by jhemmmm** [comment]
My bad, I have this function on my model Category.

```
public function subscribe()
{
return $this->morphTo();
}
```

So I was calling it like this.
```
App\Category::rememberForever()->with(['subscribe' => function($q){
  $q->rememberForever();
}])->get();
```

The query from subscribe is not cached.

**Comment by lloricode** [comment]
maybe will temporarily solve with this

```php
cache()->put(
   'category_with_subscribe', 
   App\Category::with(['subscribe'])->get(), 
   now()->addSeconds(10)
);
```

**Comment by Roywcm** [comment]
What's the status of this issue?
