### ISSUE TITLE
Call to undefined method: remember() (individual model)

### ISSUE THREAD

**Issue by nateritter** [dwightwatson/rememberable#49]
I am using the Repository pattern and want to test this trait out on just one problematic model for starters.

I have `HotelSearchRepository.php` which includes chainable methods.  The top of the file looks like this:

```
namespace App\Repositories\Eloquent;

use Watson\Rememberable\Rememberable;
use App\Repositories\Contracts\EventLocationRepositoryInterface;
use App\Repositories\Contracts\HotelSearchRepositoryInterface;

class HotelSearchRepository extends Repository implements HotelSearchRepositoryInterface
{
    use Rememberable;
...
```

I am chaining methods for my search functionality like so:

```
    public function search($terms = [])
    {
        $this->terms = $terms;

        return $this
            ->withMinSleepingRooms($this->term('min_sleeping_rooms'))
            ->withMaxSleepingRooms($this->term('max_sleeping_rooms'))
            ->withMinMeetingRooms($this->term('min_meeting_rooms'))
            ->withMinLargestMeetingRoomSqFt($this->term('min_largest_meeting_room_sq_ft'))
            ->withStarsMatching($this->term('stars'))
            ->withBrands($this->term('brands'))
            ->nearLocations($this->term('locations'), $this->term('radius'), $this->term('radius_units'))
            ->withRelatedModels()
            ->complete();
    }
```

So the method I'm including the remember trait on is here: 

```
    private function withRelatedModels()
    {
        $this->model = $this->model->with(['propertyType' => function ($q) {
            return $q->remember(10);
        }]);

        return $this;
    }
```

I am only attempting to cache the propertyType query at this point.  However, I get the exception: `Call to undefined method Illuminate\Database\Query\Builder::remember()`.

I have tried this as well, to no avail.

```
    private function withRelatedModels()
    {
        $this->model = $this->model->with(['propertyType' => function ($q) {
            return $q->remember(10);
        }])->remember(10);

        return $this;
    }
```

What am I doing wrong here?

**Comment by dwightwatson** [comment]
The trait needs to go on the Eloquent models you wish to use it on, not your repositories. It interacts directly with Eloquent internally. 

If you move it to the models it should work as you expect. Let me know if you have any other issues.

**Comment by nateritter** [comment]
I did try that and I couldn't get it to work there either. I'll try again and post results/attempts.

**Comment by nateritter** [comment]
I moved the trait to the model itself (leaving the methods alone), and still get the same error.

If I remove the eager loading bit, and just do this: 

```
    private function withRelatedModels()
    {
        // $this->model = $this->model->with(['propertyType' => function ($q) {
        //     return $q->remember(10);
        // }]);

        $this->model->remember(10);

        return $this;
    }
```
.... it doesn't throw an error, but it also isn't caching what I want.

**Comment by nateritter** [comment]
I just looked through the files that are being created and it looks like perhaps it is actually creating the right things. However, the queries are still being fired.  At least that's what DebugBar is telling me: `94 statements were executed, 30 of which were duplicated, 64 unique` every time.

**Comment by dwightwatson** [comment]
I just created a fresh Laravel app and was able to confirm that when used directly with Eloquent queries are cached are expected. I wonder if perhaps the way you're using it in your repository is causing it not to behave as expected.

When you say "it is actually creating the right things" what do  you mean? Which cache driver are you using and how are you verifying that the queries are still being run?

**Comment by nateritter** [comment]
I'm using the file driver.  I'm verifying by (1) looking in `/storage/framework/cache` (clearing it out, then reloading the page, then looking in the directory at the hash key inside each file saved), and (2) watching DebugBar to see how many queries it says it has run.

**Comment by nateritter** [comment]
From what I can see based on timestamps of the files and the hash key at the beginning of each, Rememberable is not creating more cache files on consecutive reloads, nor is it overwriting them. So, it seems to be doing it's job from that point of view.

**Comment by dwightwatson** [comment]
I just had a play with the debug bar and confirmed it works on my test app here, with cached early loading. The queries aren't being called on subsequent requests. Without full access to your app it's going to be hard to debug, I suspect there's something going on in the repository class and maybe with the way it re-assigns the model property. 

You might want to test your Eloquent code standalone as one method call and see if that does the trick.
