### ISSUE TITLE
Builder requires $minutes to be int

### ISSUE THREAD

**Issue by Ponjimon** [dwightwatson/rememberable#50]
https://github.com/dwightwatson/rememberable/blob/master/src/Query/Builder.php#L81

In that line, the Builder checks if `$minutes < 0`
This is not an error BUT:

According to the Laravel documentation, the `remember()` method requires 3 types for the first argument:
* `int`
* `float`
* ` \DateTime`

(See https://laravel.com/api/5.4/Illuminate/Cache/Repository.html#method_remember)

Is it possible to change this line so it checks for a `DateTime` instance?

What I want to achieve is the following: 

```php
Model::remember(Carbon::now()->addSeconds(30))->get();
```

This is just an example. Basically, in some cases it would be more practicable to have the possibilty to enter the expiration date as a DateTime, not in minutes (for example, if I want to use seconds instead or maybe one month as a DateTime instead of 43200 (minutes)).

**Comment by Ponjimon** [comment]
Just tested it locally, this would already "fix" it:

```php
 if (!($minutes instanceof \DateTime) && $minutes < 0) {
```

**Comment by dwightwatson** [comment]
Yeah, this seems like a fair change to make. I don't love the idea of checking if something is *not* an instance of something though, seems overly tricky. What if we flipped the code around, something like this:

```php
// If we've been given a DateTime instance or a "minutes" value that is
// greater than zero then we'll pass it on to the remember method.
// Otherwise we'll cache it indefinitely.
if ($minutes instanceof DateTime || $minutes > 0) {
    return $cache->remember($key, $minutes, $callback);
}

return $cache->rememberForever($key, $callback);
```

I can pop this on the master branch if you want to have a play with it, and then can tag it if it's stable.

**Comment by Ponjimon** [comment]
Yeah sure, I just came up with the quickest and dirtiest solution, your idea is better for obvious reasons.
Thanks!

**Comment by dwightwatson** [comment]
Cool, I've popped this onto `dev-master` so feel free to have a play. I'll try it on my apps too and if no issues in a couple of days I'll tag a new release.

**Comment by Ponjimon** [comment]
Thank you!

**Comment by dwightwatson** [comment]
Cool, this has gone out in `2.0.3`.
