### ISSUE TITLE
Check if query is cached

### ISSUE THREAD

**Issue by StevenWilliams** [dwightwatson/rememberable#51]
Is there a way to check if the query is cached? 
I want to make a command that caches commonly used queries - but if they're already cached, don't repeat the query - only repeat the query for ones that are not cached.

**Comment by dwightwatson** [comment]
I've not done anything of the sort - but getCacheKey looks to be a public method on the query builder. You should be able to use that to get the cache key for the query you're building and then check your cache driver to see if it's already been cached, then do whatever you need from there. 

Hope this helps - let me know if I can provide more help.
