### ISSUE TITLE
flushCache - flushing from wrong cache store

### ISSUE THREAD

**Issue by szwagros** [dwightwatson/rememberable#56]
Hi,

I noticed that when using flushCache non of the selected tags where flushed from redis. I believe that this is because the flushCache method takes cache store from app config:

Builder.php line 215

`$store = app('cache')->getStore();`

so if for example default cache in .env file is set to memcached, but you used redis to cache query, eg.

Model::remember(60)->cacheDriver('redis') ....

flushCache will try to flush tags from memcached instead of redis. To fix this line 215 should rather be:

`$store = app('cache')->driver($this->cacheDriver); `

So it will flush tags from store where query where cached.

**Comment by dwightwatson** [comment]
Hey - nice find. Just pushed a fix on `master`, would you have time to take a look/test if it works for your use-case and if so I'll push a tagged release.

**Comment by szwagros** [comment]
Yes - now it works correctly. Thanks !

**Comment by dwightwatson** [comment]
Sweet, tagging in `2.0.4`. Thanks for the heads up!
