### ISSUE TITLE
Empty list caching

### ISSUE THREAD

**Issue by HoffmannAndras** [dwightwatson/rememberable#57]
Hey Firstname,

Why are you cache an empty collection?

**Comment by dwightwatson** [comment]
Sorry, I don't understand your question...

**Comment by HoffmannAndras** [comment]
I try to explain.
First pageload we have an empty database, so, the concrete query's result was an empty collection.
After we migrate the database, got an empty collection again.
I think, its not too good logic for query result cache.
So if the result is an empty collection, it shouldn't be cached.

**Comment by dwightwatson** [comment]
I'm afraid I disagree. 

The whole point of query caching is to take heavy queries and prevent them from being called too frequently on the database. It is entirely possible that at times the correct result set from a query like that is simply empty.

If you're in development I probably wouldn't be using a cache driver, so your queries won't be cached. If you're in production I can't imagine you're going to be going from blank-slate to real content like that frequently enough for it to be an issue.

If this is a real problem for you I think it's the sort of logic that you're going to need to implement in your own application. Do a quick count on the database before performing your more serious query, for example.

Sorry this wasn't the answer you were after.
