### ISSUE TITLE
TRYING TO USE in SLIMEFRAMEWORK and get error: Call to undefined function Watson\Rememberable\Query\app()

### ISSUE THREAD

**Issue by ekumahost** [dwightwatson/rememberable#59]
TRYING TO USE in SLIMEFRAMEWORK and get error: Call to undefined function Watson\Rememberable\Query\app()

I have Model.php thus:
```
namespace Ekuma\Model;
use Watson\Rememberable\Rememberable;
use Illuminate\Database\Eloquent\Model as Eloquent;
abstract class Modeli extends Eloquent
{
    use Rememberable;
}
```

Then I have Cities.php thus: 
```
namespace Ekuma\Model;
class Cities extends Modeli
{
    protected $table = 'cities';

}
```

in my script I have 
`echo Cities::remember(60)->count();
`

// my composer file
```
   "autoload": {
    "psr-4": {
        "Ekuma\\": "application/"
    }
},
```

// SLIM ERROR

```
Type: Error
Message: Call to undefined function Watson\Rememberable\Query\app()
File: /Applications/XAMPP/xamppfiles/htdocs/userr/vendor/watson/rememberable/src/Query/Builder.php
Line: 182
```

**Comment by ekumahost** [comment]
"slim/slim": "^3.1",

**Comment by dwightwatson** [comment]
This package interfaces directly with Laravel and depends on the app() function provided by it. I have no plans to support use outside of Laravel - I don’t use other frameworks so I wouldn’t even know where to start. Sorry I can’t be more helpful.

**Comment by ekumahost** [comment]
I tot as much, this app() should be coming from somewhere..
