### ISSUE TITLE
I got error

### ISSUE THREAD

**Issue by ghost** [dwightwatson/rememberable#6]
local.ERROR: exception 'ErrorException' with message 'unserialize(): Error at offset 0 of 328 bytes' in vendor\laravel\framework\src\Illuminate\Cache\FileStore.php:78

**Comment by dwightwatson** [comment]
You're going to need to provide a lot more information than this. What are you trying to do, what code are you using that raises this error, what is the environment in which this error occurs. All I can see now is an error occurring in the Laravel file cache.

**Comment by ghost** [comment]
`User::where('id',$id)->remember()->get();` works after reload page that error show :cry: 

i am thinking caching driver problem.

Laravel is 5.1.10

**Comment by dwightwatson** [comment]
You do need to provide a length of time in minutes to the `remember` method - for example to cache for an hour you'd need `User::where('id', $id)->remember(60)->get();`.

**Comment by ghost** [comment]
yes it is 10 min.

`User::where('id', $id)->remember(10)->get();`
