### ISSUE TITLE
Tag inside eager load

### ISSUE THREAD

**Issue by lloricode** [dwightwatson/rememberable#61]
Hi!, is there way to add tag inside eager load?
Thanks

**Comment by dwightwatson** [comment]
You should be able to call cacheTags on the eager load query as you would normally. See here for more information: https://github.com/dwightwatson/rememberable#relationships Let me know if you have any issues.

**Comment by lloricode** [comment]
@dwightwatson , i saw that, but, a have a `polymorphic` relation, so if ever has a function that automatically  set `tag`?, 

```php
// Services
  $this->model = Model::rememberForever()
            ->cacheTags(Model::moduleName)
            ->where('status', 'enable')
            ->with(['nodes'=> function($query){
                $query->rememberForever();//->cacheTags(self::moduleName);
            }])
            ->with(['nodes'=> function($query){

                $query->rememberForever()->with(['menuable'=> function($query){
                    $query->where('status', 'enable')->rememberForever();//->cacheTags(self::moduleName);
                }]);

            }])
```

i have a boot on model 
```php
// Models
   public static function boot()
    {
        parent::boot();
        static::saved(function(Eloquent $model){
            self::flushCache(self::moduleName);
        });
    }
```

so i just want to delete a set of tags if there an update on a model,

Thanks @dwightwatson

**Comment by dwightwatson** [comment]
I don’t believe caching works on polymorphic relationships at all - there’s an open issue for this.

**Comment by lloricode** [comment]
oh i see #48,
