### ISSUE TITLE
Caching with where condition

### ISSUE THREAD

**Issue by m4a1fox** [dwightwatson/rememberable#62]
Hi. First of all, that for nice package. May be I'm not understanding cache behavior correct, but you help you clarify something. Lets assume you have such query:

`$product = (new Product())->with('plans')->whereIn('id', [1,2])->get();
dump($product);`

And I'm using traits inside Product models and Plans model with tags.

And all works fine. 

Now I have another query which looks like this

`$product = (new Product())->with('plans')->whereIn('id', [3,4])->get();
dump($product);`

So system also cached this query with same tags.

So, question. When I updates a plan model, how I can tell to flush only specific cached result, instead to flush ALL?

Thanks.

**Comment by dwightwatson** [comment]
First off, those two queries should be cached with different keys. You shouldn't end up with the same result in both. This package gets the SQL for the particular query you want to cache and uses a hash of that to generate a unique cache key. They will remain cached for however many minutes you pass into the `remember` method.

Generally you won't use this approach in combination with cache busting. If a model was to update it wouldn't be included in any existing cache responses until they expire and are regenerated. If you want additional control over that sort of caching you're probably better off using the cache driver directly.

However, you can attempt to exert control here if you really want to. You can call` getCacheKey()` on either of those queries and it will return the cache key used internally. This would allow you explicitly flush a single key from the cache. 

Hope this helps!
