### ISSUE TITLE
Query isn't cached if pluck method is used rather than get

### ISSUE THREAD

**Issue by pleek91** [dwightwatson/rememberable#63]
Hello,

Just started using this today, so maybe I'm doing something wrong but it appears that if you use the `pluck`  eloquent method the query is not cached. However, I was able to get the query to be cached by using the `get` eloquent method and then the `pluck` collection method. 

This query **will not** be cached
```
Model::remember(60)->pluck('name');
```

This query **will** be cached
```
Model::remember(60)->get()->pluck('name');
```

I would expect `Model::pluck()` (or any method that triggers the execution of a query) to be cached just like `Model::get()`. Though I imagine there is a good reason if this is intentionally not the case.

**Comment by dwightwatson** [comment]
Good find, this makes total sense. The trait overrides the get() method to handle caching, it doesn’t touch the pluck() method. Chaining get()->pluck() is the only way to handle that at the moment. 

This isn’t for any technical reason, it was just never implemented. We could override pluck() too though I find it odd it hasn’t been mentioned until now, unless people just didn’t realise that it wasn’t caching. 

Happy to look at a PR that implements this functionality.
