### ISSUE TITLE
Call to undefined method Watson\Rememberable\Query\Builder::getAuthIdentifierName()

### ISSUE THREAD

**Issue by christophmayrhofer** [dwightwatson/rememberable#64]
I just realized that my calls to 

Auth::user()

and

auth()->user()

produce the following exception:

Call to undefined method Watson\Rememberable\Query\Builder::getAuthIdentifierName()

**Comment by dwightwatson** [comment]
Have you changed anything recently that caused this error?

My initial suspicion is that this isn't related to the package - Laravel query errors generally point to the query builder when the issue actually lies somewhere else. Double check what traits you're pulling in on your user model and see if removing them fixes the issue.

**Comment by christophmayrhofer** [comment]
@dwightwatson  Thanks for pointing that out. It was another change that I made (accidentally extended User from Model instead of Authenticatable)
