### ISSUE TITLE
Caching models

### ISSUE THREAD

**Issue by freescout-helpdesk** [dwightwatson/rememberable#65]
Is it possible to cache models? https://ctf0.wordpress.com/2017/08/19/how-to-cache-models-relationships-in-laravel/

**Comment by dwightwatson** [comment]
This package doesn’t require you to interact with Laravel’s caching later directly, it doesn’t work anything like the article you posted. It automatically caches queries based on the underlying SQL produced. Please read the docs to understand the difference.

**Comment by freescout-helpdesk** [comment]
It should be possible somehow to use remember() with belongsTo in Model:
```
    public function user()
    {
        return $this->belongsTo('App\User')->remember(30);
    }
```

**Comment by dwightwatson** [comment]
Does that not work? I would expect that to work, thought it’s not something I intend to support.

The docs talk about how you can cache queries when eager loading associations on demand, rather than forcing it on the relationship.

**Comment by freescout-helpdesk** [comment]
It works. Here is how to cache related models with Rememberable:
```
class Company extends Model {

    public function user()
    {
        return $this->belongsTo('App\User');
    }

    public function user_cached()
    {
        return $this->user()->rememberForever();
    }
}
```
Now you can get cached user via `$company->user_cached` and non-cached via  `$company->user`

Very useful.
