### ISSUE TITLE
This package is very useful.Thank you. Is it support Laravel 5.8?

### ISSUE THREAD

**Issue by ramzeng** [dwightwatson/rememberable#68]
Laravel 5.8, the time to live (TTL) used when passing an integer to cache drivers will be in ‌seconds instead of minutes.

**Comment by dwightwatson** [comment]
I haven't tested with Laravel 5.8 yet but I can't think of anything that would make it incompatible. 

As it uses the standard cache driver under the hood it would now expect seconds or a DateTime instance.

We'll probably need to update the documentation to better reflect this.

Have you had a chance to test with 5.8?

**Comment by dwightwatson** [comment]
Looks fine with 5.8 to me. I'll update the docs.

**Comment by ramzeng** [comment]
Thank you very much!

**Comment by Ralla** [comment]
Works on 6.x aswell afaik
