### ISSUE TITLE
Doesn't work with pagination

### ISSUE THREAD

**Issue by LWSS** [dwightwatson/rememberable#7]

**Comment by dwightwatson** [comment]
Are you sure? Do you have an appropriate cache driver configured (i.e. you're not using the `array` cache driver)?

**Comment by LWSS** [comment]
I'm using wincache, I'm using it for Sessions too

This browse page works 

https://i.imgur.com/faJADbR.png

**Comment by dwightwatson** [comment]
If it's working for another page in your application then it's likely something in your code that is causing an issue on the page it's not working on. 

This uses the built-in Laravel caching library, so as long as you're using a driver that persists (`array` is cleared following every request) then the query will be cached correctly.

**Comment by LWSS** [comment]
I figured it out, uhh I had the same route twice, how embarassing
