### ISSUE TITLE
Overrides for prefix and driver are not working

### ISSUE THREAD

**Issue by adrienne** [dwightwatson/rememberable#71]
When i set `$rememberCachePrefix` or `$rememberCacheDriver` in my model, they quietly do nothing. Any ideas, @dwightwatson ?

**Comment by dwightwatson** [comment]
No idea, if you can post sample code that demonstrates the issue I’ll be able to look into it further.

**Comment by adrienne** [comment]
@dwightwatson 

…never mind, i'm just a dork. I was looking at the wrong model. Sorry about that.
