### ISSUE TITLE
Issue with belongsTo relationships

### ISSUE THREAD

**Issue by dmoraolazul** [dwightwatson/rememberable#77]
I added rememberable and did the following 
Model model

`<?php
namespace App;

use Watson\Rememberable\Rememberable;
use Illuminate\Database\Eloquent\Model as Eloquent;

abstract class Model extends Eloquent
{
    use Rememberable;
}`
In my model I have a relation
`$this->belongsTo('App\Brand')->rememberForever();`

Call to undefined method Illuminate\Database\Eloquent\Relations\BelongsTo::rememberForever() (View: C:\laragon\www\carsot\resources\views\partials\vehicle-item.blade.php) (View: C:\laragon\www\carsot\resources\views\partials\vehicle-item.blade.php)

**Comment by dwightwatson** [comment]
Please read the documentation - you can’t use the caching methods in relationship definitions.
