### ISSUE TITLE
laravel 6+

### ISSUE THREAD

**Issue by huangxingle2009** [dwightwatson/rememberable#79]
![image](https://user-images.githubusercontent.com/4972859/76743753-15723c80-67ae-11ea-8f7d-eacfee4c24bc.png)

**Comment by dwightwatson** [comment]
You need to install ^3.0 for Laravel 6. ^4.0 is for Laravel 7.

**Comment by clod986** [comment]
Awesome, would be a good idea to update the .README to inform users about this... thank you!
