### ISSUE TITLE
Call to undefined method: remember()

### ISSUE THREAD

**Issue by TechKat** [dwightwatson/rememberable#8]
`BadMethodCallException in Builder.php line 2025:
Call to undefined method Illuminate\Database\Query\Builder::remember()`

Am I doing something wrong?

**Comment by dwightwatson** [comment]
Sounds like you didn't include the trait, please check you've completed the installation instructions in the read me. You can either create a base model for your app that uses the trait or use it on a model-by-model basis.

**Comment by TechKat** [comment]
I have made a `Model.php` file in the `app` folder, and included the code provided on the readme page.

**Comment by dwightwatson** [comment]
Does the model you're using the remember() method on extend from the Model class in your app? Could you post any example code to illustrate the issue?

**Comment by TechKat** [comment]
`$upload::where('ext', $value)->remember(60)->count(), 'label' => str_upper($value)`

`$upload` is an instance of `\App\Upload` model, which has:

`class Upload extends Model {`

**Comment by dwightwatson** [comment]
Can you post the use statements at the top of your Upload model?

**Comment by TechKat** [comment]
Which ones?

**Comment by dwightwatson** [comment]
All of them. I think your `App\Upload` model is extending the default Laravel Model (`Illuminate\Database\Eloquent\Model`), rather than the one in your app (`App\Model`).

**Comment by TechKat** [comment]
The issue was in fact that I used the default Model statement, not the custom one. It works now.

**Comment by dwightwatson** [comment]
That's what I thought. Glad it's working now. Enjoy your caching!
