### ISSUE TITLE
cache all queries on a specific table

### ISSUE THREAD

**Issue by omidMolaverdi** [dwightwatson/rememberable#81]
As you expect, I am not a technical man. The purpose of mine is to cache all queries like DB::(TABLE)->where('XXX','YYY')->get()-ToArray() or DB::(TABLE)->whereRaw('XXX','YYY')->get()-ToArray(). Can you please guide on the steps?

**Comment by omidMolaverdi** [comment]
and also I get this error when I try to install the package:

```
    - Installation request for laravel/framework (locked at v6.18.23, required a
s ^6.2) -> satisfiable by laravel/framework[v6.18.23].
```

**Comment by dwightwatson** [comment]
To answer your first question - this package does not work when using `DB::table()` - the query builder. It only works when using Eloquent models. The README will walk you through how this works.

It sounds like you're trying to install version ~4.0, but I suspect  you'll need version ~3.0 if you want support for Laravel 6.

Hope this helps!

**Comment by omidMolaverdi** [comment]
Thanks a lot
