### ISSUE TITLE
Laravel 7 support

### ISSUE THREAD

**Issue by benjamindoe** [dwightwatson/rememberable#86]
Hi,

Is there a reason why Laravel 7 is no longer supported? Shouldn't the requirements be similar to "^7.0|^8.0"? Looks like this commit attempted to do it (c897403148cd011f2eec494e7914137efbde1ddc) but the syntax was wrong. This commit (bb5b31537b05f135c7afd7fad3d4a8a2cc0c1886) gets rid of Laravel 7 support

**Comment by dwightwatson** [comment]
Laravel 7 is still supported but not in the latest version. Just use the previous version for support.

**Comment by dwightwatson** [comment]
(4.0.0 instead of 5.0.0). 

Figured if Laravel was doing a major version jump we should too. I don’t consider the Laravel 7 version unsupported, if that helps.

**Comment by benjamindoe** [comment]
if that's the case, ^4.0 should also support PHP 8 (https://github.com/laravel/framework/blob/7.x/composer.json)

**Comment by dwightwatson** [comment]
Happy to accept a PR that adds that.

**Comment by benjamindoe** [comment]
Willing to open one, where do you want the PR sent? Master seems to be tracking 5.0 now. Can you create a 4.x branch?

**Comment by dwightwatson** [comment]
Fair point, my bad. Just branched off 4.0 and created a new release 4.0.1 that supports PHP 8.0.

**Comment by benjamindoe** [comment]
Just in case someone comes across this again, Laravel 6 probably _should_ be supported since it's LTS support until September 6th, 2022. Not tested or used Laravel 6 before so not sure what the changes are. I personally jumped from 5 to 7.
