### ISSUE TITLE
It does not work inside eager loading

### ISSUE THREAD

**Issue by rogervila** [dwightwatson/rememberable#9]
Hello, I have this code:

``` php
$posts = Post::with(['translations' => function($query){
    $query->where('lang_code', $this->lang);
}])
->with('author')
->with('tags')
->with(['images' => function($query){
    $query->with(['translations' => function($query){
    $query->where('lang_code', $this->lang);
}]);
}])
->remember(120)
->get();
```

'remember' only works before `get()` or just after `Post::`, and it remembers the first query: `select * from posts where posts.deleted_at is null`, but not the rest (so I get 5 queries instead of 6)

How can I add Remember inside the Eager Loading?
Am I missing something?

Thank you!

</code>

**Comment by dwightwatson** [comment]
You can just call `remember()` on the internal query.

```
$posts = Post::with(['translations' => function ($query) {
    $query->remember(120)->where('lang_code', $this->lang);
}]->get();
```

You could also just use the array syntax to break it down to one call to `with()`.

```
$posts = Post::with([
        'author',
        'tags',
        'translations' => function ($query) {
            $query->remember(120)
                ->where('lang_code', $this->lang);
        },
        'images' => function ($query) {
            $query->remember(120)
                ->with(['translations' => function ($query) {
                    $query->remember(120)
                        ->where('lang_code', $this->lang);
                }]);
        }
    ])
    ->remember(120)
    ->get();
```

Not the cleanest code, I know. Automatically caching the related queries is something that might be worth adding to the package, though there is a lot of flexibility in being able to control the caching of each subquery separately. I might add some information about relationship caching into the docs as I don't believe it's mentioned at all at the moment.

**Comment by rogervila** [comment]
Thank you @dwightwatson!

**Comment by sigues** [comment]
hi  @dwightwatson, this doesn't work when the eager loading is a polymorphic relationship, I've tried to fix it but haven't got any luck, should I open a new issue?

**Comment by dwightwatson** [comment]
No need, it's probably related to #48. I haven't had a chance to look at it yet, though.
